# -*- coding: utf-8 -*-
"""
Single worker process - scrapes a chunk of rows.
Called by runner.py with: python worker.py chunk.json output.csv
"""

import os
import re
import csv
import sys
import json
import time
import random
import datetime

from lxml.html import fromstring
from seleniumbase import Driver

BASE_URL = "https://www.thegreyhoundrecorder.com.au"

GROUPED_FIELDS = [
    ("Dog",     "name"),
    ("Trainer", "trainer"),
    ("Sire",    "sire"),
    ("Dam",     "dam"),
    ("Time",    "time"),
    ("Mgn",     "margin"),
    ("Split",   "split"),
    ("SP",      "sp"),
]
MAX_RUNNERS = 8

BLOCK_PHRASES = [
    "check the box if you are human",
    "request unsuccessful",
    "access denied",
    "generated by cloudfront",
    "just a moment",
    "ray id",
    "error 15",
]


def excel_serial_to_date(serial):
    base = datetime.date(1899, 12, 30)
    return base + datetime.timedelta(days=int(serial))


def dog_name_to_slug(name):
    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9\s-]", "", name)
    name = re.sub(r"\s+", "-", name)
    name = re.sub(r"-+", "-", name)
    return name.strip("-")


def date_to_site_format(d):
    return d.strftime("%d/%m/%y")


def make_driver(worker_id=0):
    import tempfile
    # Each worker gets its own user data dir to avoid Chrome profile conflicts
    user_data_dir = os.path.join(tempfile.gettempdir(), f"chrome_worker_{worker_id}_{os.getpid()}")
    os.makedirs(user_data_dir, exist_ok=True)

    chrome_args = [
        "--no-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--blink-settings=imagesEnabled=false",
        "--disable-remote-fonts",
        "--disable-blink-features=AutomationControlled",
        "--disable-features=IsolateOrigins,site-per-process",
        "--lang=en-AU",
        "--window-size=1366,768",
        f"--user-data-dir={user_data_dir}",
    ]
    return Driver(
        uc=True,
        headless=True,
        agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        chromium_arg=",".join(chrome_args),
    )


def patch_driver(driver):
    script = """
        Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
        Object.defineProperty(navigator, 'languages', {get: () => ['en-AU', 'en']});
        Object.defineProperty(navigator, 'hardwareConcurrency', {get: () => 8});
    """
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {"source": script})
        driver.execute_cdp_cmd("Emulation.setTimezoneOverride", {"timezoneId": "Australia/Sydney"})
        driver.execute_cdp_cmd("Network.setExtraHTTPHeaders", {"headers": {
            "Accept-Language": "en-AU,en;q=0.9",
        }})
    except Exception:
        pass


def warm_up(driver, log):
    log("  Warming up...")
    try:
        driver.uc_open_with_reconnect(BASE_URL, reconnect_time=6)
        time.sleep(2)
        log("  Warm-up done.")
    except Exception as e:
        log(f"  Warm-up error: {e}")


def fetch(driver, url, log, retries=3):
    for attempt in range(retries):
        try:
            driver.get(url)
            time.sleep(random.uniform(1.5, 2.5))
            for _ in range(8):
                try:
                    ready = driver.execute_script(
                        "return document.body && document.body.innerText.length > 200;")
                    if ready:
                        break
                except Exception:
                    pass
                time.sleep(0.6)
            html = driver.page_source or ""
            if html and not any(p in html.lower() for p in BLOCK_PHRASES):
                return html
            log(f"  Block detected attempt {attempt+1}/{retries} — waiting 30s...")
            time.sleep(30)
        except Exception as e:
            log(f"  Fetch error attempt {attempt+1}: {e}")
            time.sleep(5)
    return ""


def parse_dog_profile(html):
    info = {"owner": "", "trainer": "", "sire": "", "dam": "", "whelp": ""}
    try:
        tree = fromstring(html)
        sire_dam = tree.xpath('//*[contains(@class,"greyhound-info__sire-dam")]')
        if sire_dam:
            links = sire_dam[0].xpath('.//a')
            if len(links) >= 1:
                info["sire"] = links[0].text_content().strip()
            if len(links) >= 2:
                info["dam"] = links[1].text_content().strip()
        whelp_el = tree.xpath('//*[contains(@class,"greyhound-info__whelp")]')
        if whelp_el:
            m = re.search(r'whelped\s+([\d\-]+)', whelp_el[0].text_content(), re.I)
            if m:
                info["whelp"] = m.group(1)
        for span in tree.xpath('//*[contains(@class,"greyhound-info__trainer")]'):
            text = span.text_content().strip()
            if "Trainer:" in text:
                lnk = span.xpath('.//a')
                if lnk:
                    info["trainer"] = lnk[0].text_content().strip()
            if "Owner:" in text:
                m = re.search(r'Owner:\s*(.+?)$', text)
                if m:
                    info["owner"] = m.group(1).strip()
    except Exception:
        pass
    return info


def find_race_url(html, target_date, log):
    target_fmt = date_to_site_format(target_date)
    try:
        tree = fromstring(html)
        rows = tree.xpath('//table[contains(@class,"greyhound-form-racing-results__table")]//tbody/tr')
        for tr in rows:
            tds = tr.xpath('./td')
            if not tds:
                continue
            links = tds[0].xpath('.//a')
            if not links:
                continue
            if links[0].text_content().strip() == target_fmt:
                href = links[0].get("href", "")
                if href:
                    log(f"  Found: {target_fmt} -> {href}")
                    return href
    except Exception:
        pass
    log(f"  Date {target_fmt} not found in race history")
    return ""


def scrape_race_page(html):
    try:
        tree = fromstring(html)
    except Exception:
        return []
    runners = []
    for tr in tree.xpath('//tr[contains(@class,"results-event-selection")]'):
        if "scratched" in tr.get("class", ""):
            continue
        tds = tr.xpath('./td')
        def cell(i): return tds[i].text_content().strip() if i < len(tds) else ""
        plc = cell(0)
        if plc.upper() in ("SCR", "SCRATCHED"):
            continue
        box = ""
        rug = tr.xpath('.//img[contains(@alt,"Rug")]')
        if rug:
            m = re.search(r'Rug\s*(\d+)', rug[0].get("alt", ""))
            if m: box = m.group(1)
        name_span = tr.xpath('.//span[contains(@class,"results-event-selection__name")]')
        name = name_span[0].text_content().strip() if name_span else ""
        if not name or not cell(4):
            continue
        runners.append({
            "plc": plc, "name": name, "box": box,
            "trainer": cell(3), "time": cell(4),
            "margin": cell(5), "split": cell(6),
            "inrun": cell(7), "wgt": cell(8),
            "sire": cell(9), "dam": cell(10), "sp": cell(11),
        })
    return runners


def build_header():
    base = ["Date", "Name", "Sire", "Dam", "Whelp", "Trainer", "Owner"]
    for label, _ in GROUPED_FIELDS:
        for i in range(1, MAX_RUNNERS + 1):
            base.append(f"{label}{i}")
    return base


def to_row(date, dog, profile_info, runners):
    target = [r for r in runners if r["name"].lower() == dog.lower()]
    others = [r for r in runners if r["name"].lower() != dog.lower()]
    ordered = target + others
    row = [
        date, dog,
        profile_info.get("sire", ""),
        profile_info.get("dam", ""),
        profile_info.get("whelp", ""),
        profile_info.get("trainer", ""),
        profile_info.get("owner", ""),
    ]
    for _, key in GROUPED_FIELDS:
        for i in range(MAX_RUNNERS):
            if i < len(ordered):
                val = ordered[i].get(key, "")
                if key == "name":
                    val = val.upper()
                row.append(val)
            else:
                row.append("")
    return row


def log_print(worker_id, msg):
    print(f"[W{worker_id}] {msg}", flush=True)


def run_worker(worker_id, chunk, output_csv):
    log = lambda m: log_print(worker_id, m)
    log(f"Starting — {len(chunk)} rows")

    driver = make_driver(worker_id)
    patch_driver(driver)
    warm_up(driver, log)

    results = []
    failed = []

    try:
        for idx, item in enumerate(chunk):
            date_str = item["date"]
            dog_name = item["dog"]
            try:
                date = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()
            except Exception:
                log(f"Bad date {date_str} — skip")
                continue

            log(f"[{idx+1}/{len(chunk)}] {dog_name} | {date_str}")

            slug = dog_name_to_slug(dog_name)
            target_fmt = date_to_site_format(date)

            # Step 1: Discover all existing versions of this dog name
            # Check base + suffixes 1-9, collect all that exist as valid profiles
            existing = []
            for suffix in ["", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9"]:
                try_slug = slug + suffix
                candidate = fetch(driver, f"{BASE_URL}/greyhounds/{try_slug}/", log)
                if candidate and len(candidate) > 500 and "greyhound-info__heading" in candidate:
                    existing.append((try_slug, candidate))
                    log(f"  Found profile: {try_slug}")
                else:
                    if suffix != "":
                        # Once we hit a missing suffix, stop looking higher
                        break

            log(f"  Total profiles found for '{dog_name}': {len(existing)}")

            # Step 2: Search from highest version down for the target date
            html = ""
            for try_slug, candidate in reversed(existing):
                if target_fmt in candidate:
                    html = candidate
                    log(f"  Matched: {try_slug} has date {target_fmt}")
                    break
                else:
                    log(f"  {try_slug} exists but no date {target_fmt}")

            if not html:
                log(f"  No profile found with date {target_fmt} for {dog_name}")
                failed.append({**item, "reason": f"no_profile_with_date_{target_fmt}"})
                continue

            profile_info = parse_dog_profile(html)
            race_path = find_race_url(html, date, log)
            if not race_path:
                failed.append({**item, "reason": f"date_{date_str}_not_in_race_history"})
                continue

            race_html = fetch(driver, BASE_URL + race_path, log)
            if not race_html:
                failed.append({**item, "reason": "race_page_blocked_or_empty"})
                continue

            runners = scrape_race_page(race_html)
            log(f"  {len(runners)} runners")
            if not runners:
                failed.append({**item, "reason": "no_runners_on_race_page"})
                continue
            results.append((date_str, dog_name, profile_info, runners))

            time.sleep(random.uniform(0.8, 1.5))

    finally:
        try:
            driver.quit()
        except Exception:
            pass

    with open(output_csv, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(build_header())
        for date_str, dog, profile_info, runners in results:
            w.writerow(to_row(date_str, dog, profile_info, runners))

    # Write failed list
    failed_path = output_csv.replace(".csv", "_failed.json")
    with open(failed_path, "w") as f:
        json.dump(failed, f)

    log(f"Done. {len(results)} written, {len(failed)} failed.")


if __name__ == "__main__":
    worker_id = int(sys.argv[1])
    chunk_file = sys.argv[2]
    output_csv = sys.argv[3]
    with open(chunk_file) as f:
        chunk = json.load(f)
    run_worker(worker_id, chunk, output_csv)
